camel:
  springboot:
    # The Camel context name
    name: CamelRestSql

# Binding health checks to a different port
management:
  port: 8081

#server:
#  port: 8080
  
# disable all management enpoints except health
endpoints:
  enabled: false
  health:
    enabled: true

